### ISSUE TITLE
Multi edit

### ISSUE THREAD

**Issue by jankout** [madeyourday/contao-rocksolid-custom-elements#45]
I would wonder when it would be possible to use the multi editing for the custom elements. Or is it possible by now? 

Best wishes, Jan

**Comment by ausi** [comment]
The multi edit mode works currently only for standardFields, see #10

**Comment by ausi** [comment]
This feature seems impossible to implement because of how the custom elements work right now. Two elements could have a field with the same name but completely different settings which would result in a conflict.

If a specific field should work for multi edit, you can create the field via the *dcaconfig.php* and use `'inputType' => 'standardField'` in the custom elements configuration. But this only works for root level fields, not inside of lists.

**Comment by ausi** [comment]
Implemented in version 2.1.0.

It was possible to implement for root level fields. Conflicts are resolved by prefixing the field names with the custom element name. List fields still don’t work in multi edit mode.

/cc @Toflar
