### ISSUE TITLE
Field key "exclude" is not working

### ISSUE THREAD

**Issue by websolutions-hamburg** [madeyourday/contao-rocksolid-custom-elements#80]
If you use the **exclude** field key, the field is not visible including the admins.

Contao v4.4.1 & Custom Elements v2.0.3

```php
'fields' => array(
        'type' => array(
            'label' => array('Text', 'Test'),
            'exclude' => true,
            'inputType' => 'text'
        )
)
```

**Comment by ausi** [comment]
What do you want to happen if you set `'exclude' => true`?

**Comment by websolutions-hamburg** [comment]
The default defined behavior from Contao. I think this will be great. At the moment it is strange, that the the field is not visible if you set this key to true and you are an admin.

The description from Contao is:

> If true the field will be excluded for non-admins. It can be enabled in the user group module (allowed excluded fields).

https://docs.contao.org/books/api/dca/reference.html

**Comment by ausi** [comment]
This cannot work for custom element fields because all data is stored in the same column `rsce_data`. This would mean that if a non-admin user saves a custom element, the data of all excluded fields would be lost.

You can work around that by create a “native” field for *tl_content* with `'exclude' => true` and using it in the custom element via `'type' => 'standardField',`

**Comment by websolutions-hamburg** [comment]
Ah ok. Thanks for this information and the workaround tip.
